apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafanaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanaserver
  template:
    metadata:
      labels:
        app: grafanaserver
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafanaserver
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30006