apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  labels:
    app: prometheusserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheusserver
  template:
    metadata:
      labels:
        app: prometheusserver
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheusserver
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30005