apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback
  labels: 
    app: feedbacksystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedbacksystem
  template:
    metadata:
      labels:
        app: feedbacksystem
    spec:
      containers:
        - name: feedback
          image: wermuth989/exercise3-feedback
          ports:
          - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: feedback
spec:
  selector:
    app: feedbacksystem
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
      


