apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommender
  labels: 
    app: recommendersystem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendersystem
  template:
    metadata:
      labels:
        app: recommendersystem
    spec:
      containers:
        - name: recommender
          image: wermuth989/exercise3-recommender
          ports:
          - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: recommender
spec:
  selector:
    app: recommendersystem
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000

