version: "3.8"

services:
  recommender:
    build: 
      context: .
      dockerfile: ./recommender/Dockerfile
    expose: ["4000"]
    ports:
      - 4000:4000
  user_activity:
    build: 
      context: .
      dockerfile: ./user_activity_emulator/Dockerfile
    expose: ["3000"]
    ports:
      - 3000:3000
  feedback:
    build: 
      context: .
      dockerfile: ./feedback/Dockerfile
    expose: ["6000"]
    ports:
      - 6000:6000